### ISSUE TITLE
Mention in README how to purchase these

### ISSUE THREAD

**Issue by onedr0p** [diyruz/flower#17]
I know there's some fun to have these boards created but I don't know why it's not mentioned on the README. What is the current way to purchase and built these devices?

**Comment by bojanpotocnik** [comment]
I ordered them as described on the [author's article](http://modkam.ru/?p=1832)
![JLCPCB Order](https://user-images.githubusercontent.com/4901762/115794776-e249a600-a3ce-11eb-9279-945b3c080eb9.png)
That is 4.13$ delivered to my door (customs handled by JLCPCB because I selected that option and it was included in shipping price).

The only thing I needed to solder was the battery holder, which is also the easiest part to solder, or at least worth to learn a bit of soldering for the price difference.

Already happily using more than half of them :)

**Comment by jamiekris** [comment]
Is there any way now to get a hold of this kit? Does this ship from Russia?
